services:
  mysql:
    image: mysql:8.4
    container_name: aula3-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula
    ports:
      - "3306:3306"
    volumes:
      - aula3-mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PMA_HOST: aula3-mysql
      PMA_PORT: 3306
    ports:
      - "81:80"


volumes:
  aula3-mysql-data:
